package br.com.puti.core.component.packet;

/**
 * Displays the type of a packet.
 */
public enum BungeePacketType {
	
	CONNECTPLAYER,
	CUSTOM,
	GETMOTDSERVER,
	GETONLINECOUNTGLOBAL,
	GETONLINECOUNTSERVER,
	GETPLAYERIP,
	GETPLAYERNAME,
	GETPLAYERSGLOBAL,
	GETPLAYERSSERVER,
	GETPLAYERUUID,
	GETSERVERBYPLAYER,
	GETSERVERIP,
	GETSERVERS,
	ISPLAYERONLINE,
	ISSERVERONLINE,
	KEEPALIVE,
	KICKALLPLAYERS,
	KICKPLAYER,
	MESSAGEALLPLAYERS,
	MESSAGEPLAYER,
	SENDACTIONBAR,
	SENDTITLE,
	SERVERRUNNING,
	SERVERSTOPPING,
	STOPPROXY,
	WRITECONSOLE,
	UNKNOWN;
	
}
